[Variables]
;=========================================;
;===========Set These Variables===========;
;=========================================;

;===========Weather===========;

;Find your api by resgistering an account at https://openweathermap.org/appid ;
WeatherAPPID=1bf473422a2f243413f3e593a029d385

;Choose your Weather Location from https://openweathermap.org/find ;
WeatherLocation=2509951

;Choose your Weather language from https://openweathermap.org/current ;
WeatherLanguage=en

;Choose your Units: metric, imperial;
WeatherUnit=metric

;===========Disks===========;
Disk1=C:
HideDisk1=0
Disk2=D:
HideDisk2=0
Disk3=
HideDisk3=1
Disk4=
HideDisk4=1
Downloads=D:\Downloads
MyDocuments=D:\Documents

;===========Colors===========;
MainColor=255,255,255,255
SecondaryColor=255,153,51,255
;Change the color of the backgrounds;
BackgroundDateWeatherColor=0,0,0
BackgroundNetworkColor=0,0,0
BackgroundCPUColor=0,0,0
BackgroundRAMColor=0,0,0
BackgroundMediaPlayerColor=0,0,0
BackgroundFoldersAndDrivesColor=0,0,0

;===========Fonts===========;
;Choose your desired font: Open Sans, Baumans;
;You can add more fonts in resources/fonts
MainFont="Baumans"

;===========Media Player and Song info===========;
;Media Player https://docs.rainmeter.net/manual/measures/nowplaying/ check "supported players";
MediaPlayer=Spotify

; Marquee settings ;
AnimationSpeed=32
MarqueeBeginWait=1500
MarqueeEndWait=1500
; Dynamic variables - do not change ;
MarqueeTitle=0
MarqueeArtist=0


;Visibility;
; ExtendedVisibility=1
